export const SET_PROPERTY_LIST = "SET_PROPERTY_LIST";

export const SET_PROPERTY_LIST_ID = "SET_PROPERTY_LIST_ID";

export const SET_BLOG_LIST = "SET_BLOG_LIST";

export const SET_BLOG_LIST_ID = "SET_BLOG_LIST_ID";

export const SET_HOME_BLOG_LIST = "SET_HOME_BLOG_LIST";

export const SET_HOME_PROPERTY_LIST = "SET_HOME_PROPERTY_LIST";

export const SET_USER_PROFILE_LIST = "SET_USER_PROFILE_LIST";

export const SET_MY_INVESTMENT_LIST = "SET_MY_INVESTMENT_LIST";

export const SET_PROPERTY_LIKED = "SET_PROPERTY_LIKED";

export const SET_DOCUMENT_FILES = "SET_DOCUMENT_FILES";

export const SET_LOGIN = "SET_LOGIN";

export const SET_REGISTER = "SET_REGISTER";

export const SET_UPDATE_USER_DATA = "SET_UPDATE_USER_DATA";

export const SET_FORGOT_PASSWORD = "SET_FORGOT_PASSWORD";

export const SET_CONTACT_US = "SET_CONTACT_US";

export const SET_UPDATE_INVEST_LIST = "SET_UPDATE_INVEST_LIST";

export const SET_RESET_PASSWORD = "SET_RESET_PASSWORD";

export const SET_USER_LOGOUT = "SET_USER_LOGOUT";

export const SET_SINGLE_INVEST_LIST = "SET_SINGLE_INVEST_LIST";

export const SET_TEAM_LIST = "SET_TEAM_LIST";

export const SET_ABOUT_LIST = "SET_ABOUT_LIST";

export const SET_HOME_LIST = "SET_HOME_LIST";

export const SET_CLIENT_REVIEW_LIST = "SET_CLIENT_REVIEW_LIST";

export const SET_ADIVISORS_LIST = "SET_ADIVISORS_LIST";

export const SET_OUR_STORY_LIST = "SET_OUR_STORY_LIST";

export const SET_TEAM_DATA = "SET_TEAM_DATA";

export const SET_CAREAR_LIST = "SET_CAREAR_LIST";

export const SET_EVENT_WEBINARS_LIST = "SET_EVENT_WEBINARS_LIST";

export const SET_EVENT_WEBINARS_LIST_BY_ID = "SET_EVENT_WEBINARS_LIST_BY_ID";

export const SET_FAQ_LIST = "SET_FAQ_LIST";

export const SET_TERM_LIST = "SET_TERM_LIST";

export const SET_PRIVACY_LIST = "SET_PRIVACY_LIST";

export const SET_RISK_PAGE_LIST = "SET_RISK_PAGE_LIST";

export const SET_SETTING_LIST = "SET_SETTING_LIST";

export const SET_COUNTRIES = "SET_COUNTRIES";

export const SET_OLD_PROPERTY = "SET_OLD_PROPERTY";

export const SET_REFERAL = "SET_REFERAL";
